import { Product } from '../types';

type SeedProduct = Omit<Product, 'id'>;

const mealOptions = ['batata frita', 'legumes', 'verduras'];

export const initialMenu: SeedProduct[] = [
  // Meals - All default to 22$ (1 piece) and 26$ (2 pieces) unless specified
  { name: 'Carne assada', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Carne moída', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Carne ensopada', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Isca de carne', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Bife de contra filé', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Churrasquinho misto', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Filé de frango a milanesa', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Filé de frango grelhado', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Filé de frango a parmegiana', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Frango assado', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Frango ensopado com batata', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Frango ensopado com quiabo', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Estrogonofe de frango', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Estrogonofe de carne', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Filé de peixe', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: [...mealOptions, 'purê de batata'] },
  { name: 'Peixe frito (posta)', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Moela com batata', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Lombo suíno', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Carré', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Almôndegas', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: [...mealOptions, 'purê de batata'] },
  { name: 'Rabada com batata e agrião', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Costela com batata e agrião', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Empadão de frango', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Empadão de camarão', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Isca de fígado', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: [...mealOptions, 'purê de batata'] },
  { name: 'Costelinha suína', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Panqueca de carne', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  { name: 'Panqueca de frango', description: 'Acompanha arroz, feijão, macarrão e farofa.', price: 22, priceOption2: 26, category: 'refeicao', available: true, options: mealOptions },
  // Special Meals
  { name: 'Dobradinha', description: 'Única acompanhamento arroz e farofa.', price: 22, category: 'refeicao', available: true, options: [] },
  { name: 'Feijoada Pequena', description: 'Acompanha arroz, couve, farofa e laranja.', price: 35, category: 'refeicao', available: true, options: [] },
  { name: 'Feijoada Grande', description: 'Acompanha arroz, couve, farofa e laranja.', price: 50, category: 'refeicao', available: true, options: [] },

  // Drinks
  { name: 'Coca-Cola 2L', description: '', price: 15, category: 'bebida', available: true },
  { name: 'Coca-Cola 1.5L', description: '', price: 12, category: 'bebida', available: true },
  { name: 'Coca-Cola 600ml', description: '', price: 9, category: 'bebida', available: true },
  { name: 'Coca-Cola Lata', description: '', price: 7, category: 'bebida', available: true },
  { name: 'Guaracamp', description: '', price: 2.5, category: 'bebida', available: true },
  { name: 'Guaraná Antarctica 2L', description: '', price: 14, category: 'bebida', available: true },
  { name: 'Fanta Uva 2L', description: '', price: 14, category: 'bebida', available: true },
  { name: 'Fanta Laranja 2L', description: '', price: 14, category: 'bebida', available: true },
  { name: 'Sprite 2L', description: '', price: 14, category: 'bebida', available: true },
  { name: 'Água sem gás P', description: '', price: 2.5, category: 'bebida', available: true },
  { name: 'Água com gás P', description: '', price: 4, category: 'bebida', available: true },
  { name: 'Água sem gás G', description: '', price: 6, category: 'bebida', available: true },
  { name: 'Fanta Uva Lata', description: '', price: 7, category: 'bebida', available: true },
  { name: 'Fanta Laranja Lata', description: '', price: 7, category: 'bebida', available: true },
  { name: 'Guaraná Lata', description: '', price: 7, category: 'bebida', available: true },
  { name: 'Guaraviton', description: '', price: 7, category: 'bebida', available: true },
  { name: 'Sprite Lata', description: '', price: 7, category: 'bebida', available: true },
  { name: 'H2O', description: '', price: 8, category: 'bebida', available: true },
  { name: 'H2O G', description: '', price: 12, category: 'bebida', available: true },
  { name: 'Suco de maracujá', description: '', price: 10, category: 'bebida', available: true },
  { name: 'Suco de abacaxi', description: '', price: 10, category: 'bebida', available: true },
  { name: 'Suco de manga', description: '', price: 10, category: 'bebida', available: true },
];
